export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"

export const ADMIN_ORDER_REQUEST = "ADMIN_ORDER_REQUEST"
export const ADMIN_ORDER_SUCCESS = "ADMIN_ORDER_SUCCESS"
export const ADMIN_ORDER_FAIL = "ADMIN_ORDER_FAIL"


export const MYORDERS_REQUEST = "MYORDERS_REQUEST"
export const MYORDERS_SUCCESS = "MYORDERS_SUCCESS"
export const MYORDERS_FAIL = "MYORDERS_FAIL"


export const SINGLE_ORDER_REQUEST = "SINGLE_ORDER_REQUEST"
export const SINGLE_ORDER_SUCCESS = "SINGLE_ORDER_SUCCESS"
export const SINGLE_ORDER_FAIL = "SINGLE_ORDER_FAIL"


export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST"
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS"
export const UPDATE_ORDER_RESET = "UPDATE_ORDER_RESET"
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL"


export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_RESET = "DELETE_ORDER_RESET"
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERRORS"