export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"


export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST"
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS"
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL"


export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET"
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL"


export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET"
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL"


export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET"
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"


export const PRODUCT_REQUEST = "PRODUCT_REQUEST"
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
export const PRODUCT_FAIL = "PRODUCT_FAIL"


export const REVIEW_REQUEST = "REVIEW_REQUEST"
export const REVIEW_SUCCESS = "REVIEW_SUCCESS"
export const REVIEW_RESET = "REVIEW_RESET"
export const REVIEW_FAIL = "REVIEW_FAIL"


export const GET_ALL_REVIEWS_REQUEST = "GET_ALL_REVIEWS_REQUEST"
export const GET_ALL_REVIEWS_SUCCESS = "GET_ALL_REVIEWS_SUCCESS"
export const GET_ALL_REVIEWS_FAIL = "GET_ALL_REVIEWS_FAIL"


export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST"
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS"
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET"
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
